"""
Regression test: dashboard-equivalent computations must match the baseline
snapshot generated by tests/gen_no_drift_snapshot.py.

Phase 1: this test reads from model_stats.json — passes trivially.
Phase 4: this test reads from model_stats.parquet via the same logic that
the frontend will use, and must still pass byte-for-byte (within tolerance).

The "source of trades" function is parameterized so the same test body
verifies both paths.
"""
import json
import math
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SNAP_PATH = HERE / "fixtures" / "no_drift_snapshot.json"

MODELS = ["1H_5M_PREV_CISD", "30M_3M_PREV_CISD", "15M_1M_PREV_CISD"]
PROFILE = "simple_1r"
PERIODS = ["all", "2y", "1y", "6m", "3m", "1m"]


def _load_snapshot():
    if not SNAP_PATH.exists():
        pytest.skip(f"snapshot missing: {SNAP_PATH}. Run gen_no_drift_snapshot.py first.")
    return json.load(open(SNAP_PATH))


def _percentile(xs, p):
    if not xs:
        return None
    xs = sorted(xs)
    k = (len(xs) - 1) * p
    f = int(k)
    c = min(f + 1, len(xs) - 1)
    if f == c:
        return xs[f]
    return xs[f] + (xs[c] - xs[f]) * (k - f)


def _trades_from_json(model, period):
    with open(ROOT / "model_stats.json") as f:
        data = json.load(f)
    prof = data[model]["profiles"][PROFILE]
    if period == "all":
        return prof.get("recent_trades", [])
    slice_ = prof.get("by_tf", {}).get(period)
    return (slice_ or {}).get("recent_trades", [])


def _parse_full_key(full_key):
    """Decompose JSON-style key '1H_5M_PREV_CISD' into (model_key, sweep_mode, cisd_mode).

    Parquet stores these as 3 separate columns; the JSON dashboard concatenates them.
    Splitting from the right keeps the model name (which may contain underscores
    like '1H_5M') intact.
    """
    parts = full_key.rsplit("_", 2)
    if len(parts) != 3:
        raise ValueError(f"unexpected full_key shape: {full_key!r}")
    return parts[0], parts[1], parts[2]


def _trades_from_parquet(model, period):
    """Parquet-sourced trades using the same period anchor (MAX(date)) the server uses."""
    import pandas as pd
    pq = ROOT / "model_stats.parquet"
    if not pq.exists():
        pytest.skip(f"parquet missing: {pq}")
    model_key, sweep_mode, cisd_mode = _parse_full_key(model)
    df = pd.read_parquet(pq)
    df = df[
        (df["model_key"] == model_key)
        & (df["sweep_mode"] == sweep_mode)
        & (df["cisd_mode"] == cisd_mode)
        & (df["profile_key"] == PROFILE)
    ]
    # JSON `recent_trades` excludes EXPIRED setups (per CLAUDE.md: "Expired
    # setups are excluded from WR/EV but remain in the trade count"). Match
    # that semantic so drift comparisons are apples-to-apples.
    df = df[df["outcome"] != "EXPIRED"]
    if period != "all":
        # Day counts match engine's _compute_by_tf exactly (model_stats.py).
        # Using rounded year math would put 6m at 183 instead of 182 and
        # silently drift on edge days.
        days = {"2y": 730, "1y": 365, "6m": 182, "3m": 91, "1m": 30}[period]
        max_date = pd.to_datetime(df["date"]).max()
        cutoff = max_date - pd.Timedelta(days=days)
        df = df[pd.to_datetime(df["date"]) >= cutoff]
    return df.where(df.notna(), None).to_dict("records")


def _dir_summary(trades):
    out = {}
    for direction in ("long", "short"):
        sub = [t for t in trades if (t.get("direction") or "").lower() == direction]
        n = len(sub)
        if n == 0:
            out[direction] = {"n": 0, "wr": None, "ev": None, "pf": None}
            continue
        wins = [t for t in sub if t.get("outcome") == "WIN"]
        sum_win = sum(t.get("r", 0) for t in wins)
        sum_loss = sum(abs(t.get("r", 0)) for t in sub if t.get("outcome") == "LOSS")
        wr = len(wins) / n
        ev = (sum_win - sum_loss) / n
        pf = sum_win / sum_loss if sum_loss > 0 else None
        out[direction] = {
            "n": n,
            "wr": round(wr, 4),
            "ev": round(ev, 4),
            "pf": round(pf, 4) if pf is not None else None,
        }
    return out


def _close(a, b, rel=1e-3, abs_=1e-4):
    """0.1% relative tolerance for floats; exact for None/int."""
    if a is None and b is None:
        return True
    if a is None or b is None:
        return False
    if isinstance(a, int) and isinstance(b, int):
        return a == b
    if a == 0 and b == 0:
        return True
    return abs(a - b) <= abs_ + rel * max(abs(a), abs(b))


@pytest.fixture(scope="module")
def snapshot():
    return _load_snapshot()


@pytest.fixture(
    params=["json", "parquet"],
    ids=["src=json", "src=parquet"],
)
def trade_source(request):
    """Phase 1: only 'json' runs (parquet test skips if columns mismatch).
    Phase 4: both must pass."""
    return request.param


@pytest.mark.parametrize("model", MODELS)
@pytest.mark.parametrize("period", PERIODS)
def test_dir_summary_matches_snapshot(snapshot, trade_source, model, period):
    if model not in snapshot:
        pytest.skip(f"model not in snapshot: {model}")
    expected = snapshot[model][period]["dir_summary"]
    trades = _trades_from_json(model, period) if trade_source == "json" else _trades_from_parquet(model, period)
    actual = _dir_summary(trades)
    for direction in ("long", "short"):
        for field in ("n", "wr", "ev", "pf"):
            e = expected[direction][field]
            a = actual[direction][field]
            assert _close(e, a), f"{model}/{period}/{direction}.{field}: expected {e}, got {a}"


@pytest.mark.parametrize("model", MODELS)
@pytest.mark.parametrize("period", PERIODS)
def test_n_trades_matches(snapshot, trade_source, model, period):
    if model not in snapshot:
        pytest.skip(f"model not in snapshot: {model}")
    expected = snapshot[model][period]["n_trades"]
    trades = _trades_from_json(model, period) if trade_source == "json" else _trades_from_parquet(model, period)
    assert len(trades) == expected, f"{model}/{period}: expected {expected} trades, got {len(trades)}"


@pytest.mark.parametrize("model", MODELS)
@pytest.mark.parametrize("period", PERIODS)
def test_excursion_percentiles_match(snapshot, trade_source, model, period):
    if model not in snapshot:
        pytest.skip(f"model not in snapshot: {model}")
    trades = _trades_from_json(model, period) if trade_source == "json" else _trades_from_parquet(model, period)
    for field in ("mae_pct", "mfe_pct"):
        expected = snapshot[model][period][field]
        for q, p in (("p50", 0.50), ("p75", 0.75), ("p90", 0.90)):
            vals = [t.get(field) for t in trades if t.get(field) is not None]
            actual = _percentile(vals, p)
            assert _close(expected[q], actual), f"{model}/{period}/{field}.{q}: expected {expected[q]}, got {actual}"
